name: Auto Version Tag

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  auto-version-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch full history for tagging
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Extract version from setup.py
        id: extract-version
        run: |
          # Extract version from setup.py using the dedicated script
          VERSION=$(python .github/scripts/extract_version.py)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
      
      - name: Check if tag already exists
        id: check-tag
        run: |
          VERSION="${{ steps.extract-version.outputs.version }}"
          if git tag -l "$VERSION" | grep -q "$VERSION"; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Tag $VERSION already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Tag $VERSION does not exist"
          fi
      
      - name: Create and push tag
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          VERSION="${{ steps.extract-version.outputs.version }}"
          TAG_NAME="$VERSION"
          
          # Configure git for tagging
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create annotated tag
          git tag -a "$TAG_NAME" -m "Release version $VERSION"
          
          # Push the tag
          git push origin "$TAG_NAME"
          
          echo "Successfully created and pushed tag: $TAG_NAME"
      
      - name: Skip tag creation
        if: steps.check-tag.outputs.exists == 'true'
        run: |
          echo "Tag ${{ steps.extract-version.outputs.version }} already exists, skipping creation"
